# Phase 1 Orchestrator - Konfiguration

# Pfade
paths:
  # Input
  gliederung_json: "input/output-phase0.5-final.json"
  prompt_template: "templates/prompt-phase1.md"
  example_sections: "templates/example-sections"
  
  # Output
  output_prompts: "output/prompts"
  output_contexts: "output/contexts"
  output_sections: "output/sections"
  
  # Ressourcen
  strategiedokument: "../Strategiedokument_Beispiel__AXIOM_Examine.md"
  terminologie: "../Terminologie-Entscheidungsliste.md"
  html_template_spec: "../Phase_1__HTML-Template_Spezifikation__Matroschka-Prinzip_.md"
  json_schema: "../main-content_schema.json"

# Validierung
validation:
  check_json_ld: true
  check_html_syntax: true
  check_bfsg: true
  check_links: true
  check_terminology_tags: true
  
  # Strenge
  fail_on_warnings: false  # true = Warnung = Abbruch
  fail_on_errors: true

# Kontext-Extraktion
context:
  num_predecessors: 2  # Anzahl Vorgänger-Sections
  num_successors: 2    # Anzahl Nachfolger-Sections
  include_prerequisites: true
  include_cross_refs: true

# Workflow
workflow:
  auto_continue: false  # true = kein manueller Input zwischen Sections
  save_contexts: true   # Kontexte als JSON speichern (Debug)

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/orchestrator.log"
